### PR TITLE
Mb python v5

### PR DESCRIPTION
**Pull request by matthewbaker22**
git fetch --all
git checkout MB-python-V5

check that when cultivating plant, all errors are accounted for

### CODE REVIEW

**Review by Iandonmorgan — CHANGES_REQUESTED** [review]
update messaging to display a little more info...
previous: "Not gonna happen"
updated: "The {environment.name} is not a suitable environment for the {animal.species}

**Review by Iandonmorgan — APPROVED** [review]
👍

**Review by castlesmadeofcode — APPROVED** [review]
NICE

**Review by CoopNich — APPROVED** [review]
This makes me feel things

**Pull request merged**
