### PR TITLE
Arboretum clean up

### PR DESCRIPTION
**Pull request by Iandonmorgan**
1. git fetch --all
2. look at arboretum.py
3. confirm class contains lists for each kind of biome that you want to assign animals or plants to.

### CODE REVIEW

**Comment by castlesmadeofcode** [comment]
looks good!

**Comment by matthewbaker22** [comment]
👍

**Review by CoopNich — APPROVED** [review]
oh baby yeah

**Review by matthewbaker22 — APPROVED** [review]
Looks good!

**Review by castlesmadeofcode — COMMENTED** [review]
looks good!

**Pull request merged**
